# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd33cfcf83585a4ec73a7b86714d8edb19333165a6db9347600753bba18279afccb3df68c13e93dbf03e0c81aa85b4444e891f972a1e7db1150a0546ffebb794

test:
  secret_key_base: 3095fd4da754266b9eda2b22e2b41e97c7a41f622c48d220ad33ec604d49ccf581a39f2a4fee4ff155e50eb4977f83bbddc3c34811f66b0ed4d43193d9dd3185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
